TextExpression : decodeBase64ToReference(reportBytes)
XpathExpression : oraext:decodeBase64ToReference($RunBIPReport/tns:runReportResponse/tns:runReportReturn/tns:reportBytes)
NamespaceList : tns=http://xmlns.oracle.com/oxp/service/PublicReportService oraext=http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc
NumberOfWarnings : 0
NumberOfErrors : 0
ExpressionName : 
VariableName : 
VariableDescription : 
VariableType : 
VariableTypeNamespace :